services:
  pg:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: avito_coins
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - test_app_network

  fastapi_app:
    build: .
    container_name: avito_fastapi
    restart: always
    depends_on:
      - pg
    environment:
      # DATABASE_URL: "postgresql+asyncpg://user:password@pg:5432/avito_coins"
      DOCKER_ENV: "true"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c", "/wait-for-it.sh pg 5432 -- poetry run uvicorn avito.main:main_app --host 0.0.0.0 --port 8080"]    
    networks:
      - test_app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - pg
    networks:
      - test_app_network

volumes:
  pg_data:

networks:
  test_app_network:
    driver: bridge
