 services:
  pg:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: avito_coins
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  fastapi_app:
    build: .
    container_name: avito_fastapi
    restart: always
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql://user:password@pg:5432/avito_coins
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - pg

volumes:
  pg_data:
