"""Add extend_existing to Base

Revision ID: 57e0a1b351d0
Revises: b8750c54fa04
Create Date: 2025-03-06 18:31:00.177365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57e0a1b351d0"
down_revision: Union[str, None] = "b8750c54fa04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
