"""Make username field non unique

Revision ID: 760cd12a46fb
Revises: 4c5663349944
Create Date: 2025-02-14 12:55:21.248619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "760cd12a46fb"
down_revision: Union[str, None] = "4c5663349944"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_username", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_username", "users", ["username"])
    # ### end Alembic commands ###
