"""Added email column to Users

Revision ID: 4c5663349944
Revises: f9202fa5959d
Create Date: 2025-02-13 23:36:33.136787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c5663349944"
down_revision: Union[str, None] = "f9202fa5959d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=320),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_index("ix_users_email", table_name="users")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=320),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
